version: "3.8"

services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
    depends_on:
      - postgesql
    restart: always

  postgesql:
    image: postgres:15-alpine
    container_name: api_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
