DROP TABLE IF EXISTS todos CASCADE;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE todos
(
    id UUID PRIMARY KEY         DEFAULT uuid_generate_v4(),
    title    VARCHAR(512)  NOT NULL CHECK ( title <> '' ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS todos_title_idx ON todos (title);
